### ISSUE TITLE
Language dll in ANSI mode only

### ISSUE THREAD

**Issue by Arkshine** [kapilratnani/DocIt#1]
Hi, 

It seems that you can choose ANSI/UNICODE for the main dll, but for the language dll, it's only and always in ANSI.

Quite a problem.

Thanks.

**Comment by kapilratnani** [comment]
Hi,
     Now, For the main dll, ANSI build option was in the notepad++ plugin template, that is why it is still there. I've never provided/tried a build for it as ANSI version of notepad++ was long deprecated. It only builds for UNICODE.

For language dll, they are all built with unicode from the beginning.

Thank you.

**Comment by Arkshine** [comment]
I want the language dll in UNICODE. When I compile, and copy-paste the .dll to Np++, it says the language dll is an ANSI version and can't be loaded. That's why I'm asking here because NP++ says the contrary. Note it doesn't happen for the main dll. Sorry for the title, but I don't care about ANSI and btw should be removed from your project since no more supported by NP++.

**Comment by kapilratnani** [comment]
That is strange, this has never been reported before. I've changed the project settings, tested the resulting build and it all works fine. I've pushed the code, have a look..

**Comment by Arkshine** [comment]
It still happens : http://img838.imageshack.us/img838/401/20120615223823.jpg 

Let me try with the original NP++ version, just to see.

**Comment by kapilratnani** [comment]
yes, download it from the sourceforge page..

**Comment by Arkshine** [comment]
Tried, with the original version and it still happens.

**Comment by Arkshine** [comment]
Just to show a visual : http://img407.imageshack.us/img407/1060/20120615224450.png

**Comment by kapilratnani** [comment]
ohh..i got the problem.. actually those files should be in a folder called "nppdocitplugins". The language dlls are loaded by the main dll from that folder.

**Comment by Arkshine** [comment]
It works yes. :P
Kind of confused because others files were containing. I did not think the folder was needed.

**Comment by kapilratnani** [comment]
Notepad++ recognizes it as an invalid plugin file and raises that not so clear message. The language dlls are plugins for DocIt. All DocIt plugins go in "nppdocitplugins" directory. My bad no documentation exists for this..

**Comment by Arkshine** [comment]
No problem. Good to know. Now, I can _try_ to play with the regex.
